INSERT INTO MPA (NAME) VALUES('G');
INSERT INTO MPA (NAME) VALUES('PG');
INSERT INTO MPA (NAME) VALUES('PG-13');
INSERT INTO MPA (NAME) VALUES('R');
INSERT INTO MPA (NAME) VALUES('NC-17');

INSERT INTO GENRE (GENRE_NAME) VALUES('Комедия');
INSERT INTO GENRE (GENRE_NAME) VALUES('Драма');
INSERT INTO GENRE (GENRE_NAME) VALUES('Мультфильм');
INSERT INTO GENRE (GENRE_NAME) VALUES('Триллер');
INSERT INTO GENRE (GENRE_NAME) VALUES('Документальный');
INSERT INTO GENRE (GENRE_NAME) VALUES('Боевик');
